### ISSUE TITLE
As a owner, I want to populate the property upload form with information from the uploaded Excel sheet, so that I can quickly and efficiently enter property details.

### ISSUE THREAD

**Issue by haejoonchoi** [yoo-ran/goldenkey#5]
@yoo-ran

this one also doesn't need to have ",so that" part. 
I think you can just say "... I want to be able to add details onto Excel-sheet-generated properties.
@haejoonchoi

**Comment by yoo-ran** [comment]
# Title : Populate property form with data from uploaded Excel

## Condition of Success
- [ ] Add "Upload Excel" Feature
- [ ] Parse Excel Data
- [ ] Populate Form Fields
- [ ] Handle Form Submission
